### ISSUE TITLE
Private browsing support

### ISSUE THREAD

**Issue by rainemak** [sailfishos/sailfish-browser#202]
Enable private browsing support.

As we have a history that is at browser side we cannot write to the history when private browsing is enabled.

Preference:
"browser.privatebrowsing.autostart"

Some pointers to Gecko:

* https://github.com/tmeshkova/gecko-dev/blob/embedlite/embedding/components/windowwatcher/nsWindowWatcher.cpp#L424

* https://github.com/tmeshkova/gecko-dev/blob/embedlite/dom/ipc/TabChild.cpp#L1012

* https://github.com/tmeshkova/gecko-dev/blob/embedlite/dom/ipc/TabChild.cpp#L812

**Comment by rojkov** [comment]
It seems the UX people are OK with implementing private browsing through having Private Mode.

Basically it means that
 1. the pull-down menu of the Tabs view should get a new menu item "Private mode";
 2. clicking this item should switch the browser into the private mode;
 3. in the private mode the Tabs view lists only "private" tabs and the mentioned menu items transforms into "Normal mode" (the translation team will define the final wording);
 4. "Private mode" is indicated in the Tabs view and in the toolbar (the exact indication is TBD);
 5. all data structures belonging to the private tabs are in-memory and must not outlive the browser process;
 6. when in the private mode all new tabs are created as private ones;
 7. upon restart the browser should be in the normal mode.

The point 3 implies that we need to implement a separate `DeclarativeTabModel` for private tabs. This model class must not use the DB manager.

I would personally prefer to keep the current mode in a singlatone instance of some `GlobalState` class rather than in an attribute of `DeclarativeWebContainer` or `BrowserPage`. The ratio is that
 1. it easier to remember that global state is maintained in `GlobalState`;
 2. no need to worry about how to propagate the value to underlying components;
 3. `DeclarativeWebUtils` is semantically overloaded at the moment - at least its debugMode attribute could go the `GlobalState` as well.

Also the point 5 means that private tabs' thumbnails must not be flushed to a file.
